### ISSUE TITLE
About liftover

### ISSUE THREAD

**Issue by greekkey** [dmiller903/CompoundHetVIP#5]
Hi dmiller903. It's me again. By our last discussion, I applied CompoundHetVIP to a number of exome sequencing gvcf files.
I noticed that the final output files were in hg19 coordination.
Because my original bam files and vcf files were all in hg38, I then decided to convert the output of CompoundHetVIP back to hg38. 
To my surprise, some of the sites failed in liftover. 
Here are some of them:

> #Partially deleted in new
chr1:156354347-156354348
#Partially deleted in new
chr7:72209527-72209528
#Deleted in new
chr7:142250938-142250938
#Deleted in new
chr7:142250988-142250988
#Partially deleted in new
chr11:70798924-70798931
#Partially deleted in new
chr12:11420333-11420334
#Partially deleted in new
chr19:54973988-54973991
#Partially deleted in new
chr19:56599437-56599440

I am now confused because the input of CompoundHetVIP were all converted from hg38 but some of the output after filtering could not be converted back. 

Best,
Jacob

**Comment by dmiller903** [comment]
Hi Jacob,

Is it a small number that don’t transfer back over, like 3-4%? Also, during leftover are you using the exact same reference genome that the original data were aligned to? What tool are you using to liftover? Are you lifting over a VCF or different file type?

**Comment by greekkey** [comment]
Hi dmiller,
 Yes, only very few sites in the *_gemini.tsv file failed in transfer back, e.g.. only 8 of 14100 sites in the sample I tested failed. 
 I also did liftover for the final results (identified CH or denove variants) of over 200 exomes. These sites were all OK.

 I did liftover using UCSC webpage by uploading a BED file generated from the *_gemini.tsv;  my original data were aligned to "Homo_sapiens_NCBI_GRCh38Decoy". So the reference genome may be slightly different, I guess?

Jacob

**Comment by dmiller903** [comment]
I just took a GRCh38 vcf from GIAB and used the liftover step of CompoundHetVIP to lift to GRCh37, then I used Picard's liftover tool (same tool CompoundHetVIP uses) to lift back to GRCh38 using a reference genome I got from UCSC. Of the 4027435 variants in the file, 231 did not lift back over to GRCh38. So yes, I'm guessing that some positions weren't lifted back due to the use of a slightly different build of the reference genome than what was originally used during alignment, or the chain file doesn't have all the positions available for liftover, or a limitation in the liftover software. So it seems strange that not all positions would lift back, but isn't abnormal.

**Comment by greekkey** [comment]
Hi Miller. Thank you for the detailed explanation. I did not encountered this problem in lifting over the final result tsv files; it only occurred for very few variants of the *_gemini.tsv files. So I think I should discard those variants for they may not reliable and after all the *.gemini files are just an intermediates. 
But I strongly suggest you add a step somewhere to convert back to hg38 in case the user started from hg38. After all, they may need to check the results in their original bam files, so it's better to keep the coordination same. 
Thank you very much again for your kind help!
Jacob
